### ISSUE TITLE
Css render

### ISSUE THREAD

**Issue by brianpursell** [brianpursell/magic-box#6]
Get css to render on the live server

**Comment by JoshuaBrigati** [comment]
At the moment webpack needs to be chnaged to this:

`var path = require('path');
var SRC_DIR = path.join(__dirname, '/react-client/src');
var DIST_DIR = path.join(__dirname, '/react-client/dist');

module.exports = {
  entry: `${SRC_DIR}/index.jsx`,
  output: {
    filename: 'bundle.js',
    path: DIST_DIR
  },
  module : {
    loaders : [
      {
        test : /\.jsx?/,
        include : SRC_DIR,
        loader : 'babel-loader',      
        query: {
          presets: ['react', 'es2015']
       }
      }
    ]
  }
};`

And then run: 

npm install css-loader style-loader sass-loader node-sass --save-dev
